name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install

      - name: Check that library can build / compile
        run: yarn build

      - name: Run style / linting tests
        run: yarn lint

      - name: Run unit tests
        run: yarn test
